const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.0' });

const doc = {
    info: {
        title: 'API Documentation',
        description: 'Automatically generated by Swagger Autogen',
        version: '1.0.0',
    },
    servers: [
        {
            url: 'http://113.198.66.75:443',
            description: 'Production server',
        },
    ],
    components: {
        schemas: {
            Job: {
                type: 'object',
                properties: {
                    회사명: { type: 'string', required: true, example: '테크스타트업' },
                    제목: { type: 'string', required: true, example: '백엔드 개발자 채용' },
                    링크: { type: 'string', format: 'url', required: true, example: 'https://example.com/job' },
                    마감일: { type: 'string', format: 'date', required: true, example: '2024-12-31' },
                    지역: { type: 'string', example: '서울' },
                    경력: { type: 'string', example: '3년 이상' },
                    학력: { type: 'string', example: '대학교 졸업' },
                    고용형태: { type: 'string', example: '정규직' },
                    직무분야: { type: 'string', example: '백엔드' },
                    연봉정보: { type: 'string', example: '연봉 4000~5000만원' },
                    조회수: { type: 'integer', example: 100 },
                },
                required: ['회사명', '제목', '링크', '마감일'],
            },
            JobWithCompany: {
                type: 'object',
                properties: {
                    회사명: { type: 'string', required: true, example: '테크스타트업' },
                    제목: { type: 'string', required: true, example: '백엔드 개발자 채용' },
                    링크: { type: 'string', format: 'url', required: true, example: 'https://example.com/job' },
                    마감일: { type: 'string', format: 'date', required: true, example: '2024-12-31' },
                    지역: { type: 'string', example: '서울' },
                    경력: { type: 'string', example: '3년 이상' },
                    학력: { type: 'string', example: '대학교 졸업' },
                    고용형태: { type: 'string', example: '정규직' },
                    직무분야: { type: 'string', example: '백엔드' },
                    연봉정보: { type: 'string', example: '연봉 4000~5000만원' },
                    조회수: { type: 'integer', example: 100 },
                    회사정보: {
                        type: 'object',
                        properties: {
                            링크: { type: 'string', format: 'url', example: 'https://company.com' },
                            지역: { type: 'string', example: '부산' },
                            직무분야: { type: 'string', example: '프론트엔드' },
                            연봉정보: { type: 'string', example: '연봉 3000~4000만원' },
                        },
                    },
                },
                required: ['회사명', '제목', '링크', '마감일', '회사정보'],
            },
            Application: {
                type: 'object',
                properties: {
                    userId: { type: 'string', required: true, example: '647f1a2b3c4d5e6f7g8h9i0j' },
                    회사명: { type: 'string', required: true, example: '테크스타트업' },
                    링크: { type: 'string', format: 'url', required: true, example: 'https://example.com/job' },
                    지원시간: { type: 'string', format: 'date-time', example: '2024-12-15T14:30:00Z' },
                },
                required: ['userId', '회사명', '링크'],
            },
            Bookmark: {
                type: 'object',
                properties: {
                    userId: { type: 'string', required: true, example: '647f1a2b3c4d5e6f7g8h9i0j' },
                    회사명: { type: 'string', required: true, example: '테크스타트업' },
                    링크: { type: 'string', format: 'url', required: true, example: 'https://example.com/job' },
                },
                required: ['userId', '회사명', '링크'],
            },
            User: {
                type: 'object',
                properties: {
                    이메일: { type: 'string', format: 'email', required: true, example: 'user@example.com' },
                    비밀번호: { type: 'string', required: true, example: 'password123' },
                    이름: { type: 'string', required: true, example: '홍길동' },
                    createdAt: { type: 'string', format: 'date-time', example: '2024-12-15T14:30:00Z' },
                    refreshToken: { type: 'string', example: 'refresh-token-example' },
                    lastLogin: { type: 'string', format: 'date-time', example: '2024-12-15T14:30:00Z' },
                },
                required: ['이메일', '비밀번호', '이름'],
            },
            ApplicationWithUser: {
                type: 'object',
                properties: {
                    userId: { type: 'string', required: true, example: '647f1a2b3c4d5e6f7g8h9i0j' },
                    회사명: { type: 'string', required: true, example: '테크스타트업' },
                    링크: { type: 'string', format: 'url', required: true, example: 'https://example.com/job' },
                    지원시간: { type: 'string', format: 'date-time', example: '2024-12-15T14:30:00Z' },
                    지원자정보: {
                        type: 'object',
                        properties: {
                            이메일: { type: 'string', format: 'email', example: 'user@example.com' },
                            이름: { type: 'string', example: '홍길동' },
                        },
                    },
                },
                required: ['userId', '회사명', '링크', '지원자정보'],
            },
            BookmarkWithUser: {
                type: 'object',
                properties: {
                    userId: { type: 'string', required: true, example: '647f1a2b3c4d5e6f7g8h9i0j' },
                    회사명: { type: 'string', required: true, example: '테크스타트업' },
                    링크: { type: 'string', format: 'url', required: true, example: 'https://example.com/job' },
                    사용자정보: {
                        type: 'object',
                        properties: {
                            이메일: { type: 'string', format: 'email', example: 'user@example.com' },
                            이름: { type: 'string', example: '홍길동' },
                        },
                    },
                },
                required: ['userId', '회사명', '링크', '사용자정보'],
            },
        },
    },
};

const outputFile = './swagger/swagger-output.json';
const endpointsFiles = ['./app.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
