const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
        title: 'API Documentation',
        description: 'Automatically generated by Swagger Autogen',
    },
    host: '113.198.66.75:443', // 서버 호스트
    schemes: ['https'], // 사용 프로토콜 (http/https)
};

const outputFile = './swagger/swagger-output.json'; // 생성될 Swagger 파일
const endpointsFiles = ['./app.js']; // 엔드포인트가 정의된 파일

swaggerAutogen(outputFile, endpointsFiles,doc);
